### ISSUE TITLE
can you provide dataset?

### ISSUE THREAD

**Issue by noelcodes** [SathwikTejaswi/deep-image-similarity-ranking#2]
can you provide dataset? 
I want them in order to generate train_embeddings.npy and test_embeddings.npy.

**Comment by noelcodes** [comment]
OK found it:
https://tiny-imagenet.herokuapp.com/

But I ran python train_embedding.py, thrown me error no matter where I place the dataset.... ha ha..

`
python train_embedding.py

libraries imported
loading training data...
Traceback (most recent call last):
  File "train_embedding.py", line 87, in <module>
    Tiny = Tiny('tiny-imagenet-200/val')
  File "train_embedding.py", line 52, in __init__
    for i,j in enumerate(os.listdir(os.path.join(self.root_dir))):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'tiny-imagenet-200/val'`

**Comment by SathwikTejaswi** [comment]
Hi,
This is the link to the dataset : http://cs231n.stanford.edu/tiny-imagenet-200.zip

**Comment by SathwikTejaswi** [comment]
For the FileNotFoundError, you have to replace 'tiny-imagenet-200/val' with the path to the dataset on your system!
