### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by kashyap32** [SathwikTejaswi/deep-image-similarity-ranking#3]
I can't run train_embedding.pr or model.py.
It throws me error - No such file or directory: 'modelresnewnew3.ckpt'

**Comment by hodaatef** [comment]
i have same error , No such file or directory: 'modelresnewnew3.ckpt'
how produce this file
please any one help me

**Comment by hodaatef** [comment]
@kashyap32  did you solve the error

**Comment by SathwikTejaswi** [comment]
@kashyap32 that is the path to the pretrained weights. Just comment the line where model weights are being loaded and it should work!
